Update README.md: Guidance for Customizing Upload Limits
linuxserver/docker-lychee pull request #65
Opened 2023-05-24 00:36 UTC by ZarTek-Creole

This commit adds a new section to the README.md file to provide users with guidance on how to customize upload limits in Lychee Docker container. This update is a follow-up to pull request https://github.com/linuxserver/docker-lychee/pull/64, where it was suggested that instead of changing default settings, it would be more beneficial to provide clear instructions to users on how to make this change themselves. 

The new section includes step-by-step instructions on modifying the `user.ini` file, as well as the necessary commands to restart the Docker container for the changes to take effect. It also adds a note of caution, reminding users that changing these settings may impact their server's performance.

2023-05-24 02:40 UTC, nemchik requested changes, later dismissed
Please note:
https://github.com/linuxserver/docker-lychee/blob/1bb561ce5bc9cb51c19cd3118b12089359ece9a1/README.md?plain=1#L1-L2

You need to edit the `app_setup_block` section here https://github.com/linuxserver/docker-lychee/blob/1bb561ce5bc9cb51c19cd3118b12089359ece9a1/readme-vars.yml#L84

2023-05-24 09:03 UTC, ZarTek-Creole commented
I apologize for any confusion caused by the previous commits. This commit corrects the application setup instructions in the `readme-vars.yml` file. It provides guidance on customizing Lychee's upload limit to cater to individual server needs. I hope this addresses the concerns raised in the previous discussion, and I appreciate your patience and understanding. Thank you.

2023-05-24 09:13 UTC, Roxedus requested changes
I would like to keep the usage of emojis unified across all our readmes.

2023-05-24 09:13 UTC, Roxedus commented on readme-vars.yml
> +  ## 🛠️ Customization
```suggestion
  ## Customization
```

2023-05-24 09:13 UTC, Roxedus commented on readme-vars.yml
> +  In certain scenarios, you might need to change the default settings of Lychee. For instance, if you encounter limitations when uploading large files, you can increase this limit. 📈
```suggestion
  In certain scenarios, you might need to change the default settings of Lychee. For instance, if you encounter limitations when uploading large files, you can increase this limit.
```

2023-05-24 09:13 UTC, Roxedus commented on readme-vars.yml
> +  ### 📤 Increasing Upload Limit
```suggestion
  ### Increasing Upload Limit
```

2023-05-24 09:13 UTC, Roxedus commented on readme-vars.yml
> +  #### 🔁 Via Docker Compose
```suggestion
  #### Via Docker Compose
```

2023-05-24 09:13 UTC, Roxedus commented on readme-vars.yml
> +  #### 🔁 Via Docker Run
```suggestion
  #### Via Docker Run
```

2023-05-24 09:13 UTC, Roxedus commented on readme-vars.yml
> +  ⚠️ Please note that these changes might have implications on your server's performance, depending on its available resources. Thus, it's recommended to modify these settings with caution.
```suggestion
  **Please note that these changes might have implications on your server's performance, depending on its available resources. Thus, it's recommended to modify these settings with caution.**
```

2023-05-27 14:28 UTC, Roxedus requested changes
Sorry, should have caught the levels of markdown sooner, this all belongs under `Application Setup`, which is at level 2

2023-05-27 14:28 UTC, Roxedus commented on readme-vars.yml
> +  ## Customization
```suggestion
  ### Customization
```

2023-05-27 14:28 UTC, Roxedus commented on readme-vars.yml
> +  ### Increasing Upload Limit
```suggestion
  #### Increasing Upload Limit
```

2023-05-27 14:28 UTC, Roxedus commented on readme-vars.yml
> +
This should be self-explanatory
```suggestion
```

2023-05-30 13:13 UTC, Roxedus approved these changes

2023-05-30 13:19 UTC, merged